---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cwashburn/environment-to-yaml
outputs:
- name: product-secrets
run:
  path: environment-to-yaml
  args: [ "generate", "--environment-prefix", "PRODUCT", "--output-file", "product-secrets/product.yml" ]
