---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/tile-config-generator
inputs:
- name: tile-config-generator
- name: product
- name: environments
- name: product-secrets
  optional: true
params:
  OM_HOST:
  OM_USERNAME:
  OM_PASSWORD:
  OPS_FILES:
  VARS_FILES:
run:
  path: tile-config-generator/tasks/install-product.sh
