---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/tile-config-generator
inputs:
- name: product
outputs:
- name: config
params:
  OPS_FILES:
run:
  path: bash
  args:
    - -c
    - |
      set -ex
      echo "Use om tool directly as it supports operations files"
      exit 1
      pivotal_file=$(find product -name '*.pivotal')
      tile-config-generator generate --pivotal-file-path ${pivotal_file} --base-directory config --do-not-include-product-version

      tile-config-generator display --pivotal-file-path ${pivotal_file}

      ops_files_args=""
      for op in ${OPS_FILES}
      do
        ops_files_args+=("-o config/${op}")
      done

      tmp=$(mktemp)
      bosh int config/product.yml ${ops_files_args[@]} > ${tmp}
      cp ${tmp} config/product.yml
