---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/tile-config-generator
outputs:
- name: config
params:
  OPS_FILES:
  PIVNET_TOKEN:
  PIVNET_PRODUCT_SLUG:
  PIVNET_PRODUCT_VERSION:
  PIVNET_PRODUCT_GLOB: *.pivotal
run:
  path: bash
  args:
    - -c
    - |
      set -ex
      tile-config-generator generate --base-directory config --do-not-include-product-version --include-errands pivnet

      tile-config-generator display pivnet

      ops_files_args=""
      for op in ${OPS_FILES}
      do
        ops_files_args+=("-o config/${op}")
      done

      tmp=$(mktemp)
      bosh int config/product.yml ${ops_files_args[@]} > ${tmp}
      cp ${tmp} config/product.yml
