---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/tile-config-generator
inputs:
- name: config
outputs:
- name: transformed-config
params:
  OPS_FILES:
run:
  path: bash
  args:
    - -c
    - |
      set -ex
      echo "Use om tool directly as it supports operations files"
      exit 1
      ops_files_args=""
      for op in ${OPS_FILES}
      do
        ops_files_args+=("-o config/${op}")
      done

      cp config/*-vars.yml transformed-config/.
      bosh int config/product.yml ${ops_files_args[@]} > transformed-config/product.yml
